[package]
name = "delonix-vm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
delonix-node = { workspace = true }
delonix-model = { workspace = true }
delonix-state = { workspace = true }
delonix-compute = { workspace = true }
delonix-net-rules = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
libc = { workspace = true }

[lints]
workspace = true
