//! The Linux provider's answer to the capability catalog for CONTAINERS and
//! pods (`delonix_compute::capability`, ADR-0050) — the kernel is the
//! provider, this adapter is how the engine drives it.
//!
//! Same discipline as the VM backends: an exhaustive `match`, evidence on
//! every `Supported`, and a probe struct so the same declaration renders
//! against an assumed host (the published matrix) and against this machine.

use delonix_compute::capability::{
    Capability as C, CapabilityState as S, HealthStatus, ProviderHealth, ProviderKind,
    ProviderReport,
};
use delonix_compute::capability_host::binary_in_path;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LinuxHost {
    pub rootless: bool,
    /// Limits reach a cgroup the engine can write (delegated scope, or root).
    pub cgroup_delegated: bool,
    /// `newuidmap`/`newgidmap` present — a rootless user namespace with more
    /// than one uid.
    pub subid_tools: bool,
    /// `nvidia-ctk` present: CDI specs can exist on this host.
    pub nvidia_ctk: bool,
}

impl LinuxHost {
    pub const ASSUMED: LinuxHost = LinuxHost {
        rootless: true,
        cgroup_delegated: true,
        subid_tools: true,
        nvidia_ctk: true,
    };

    /// Reads this machine. The delegation probe creates and removes one empty
    /// cgroup; nothing else has a side effect.
    pub fn probe() -> LinuxHost {
        LinuxHost {
            rootless: super::is_rootless(),
            cgroup_delegated: super::cgroup_limits_apply(),
            subid_tools: binary_in_path("newuidmap") && binary_in_path("newgidmap"),
            nvidia_ctk: binary_in_path("nvidia-ctk"),
        }
    }
}

pub fn report(host: &LinuxHost) -> ProviderReport {
    let (status, reason, message) = if host.rootless && !host.subid_tools {
        (
            HealthStatus::Healthy,
            "SingleUidMapping",
            "newuidmap/newgidmap missing: the user namespace maps one uid only (install uidmap)"
                .to_string(),
        )
    } else if !host.cgroup_delegated {
        (
            HealthStatus::Healthy,
            "CgroupNotDelegated",
            "resource limits are best-effort in this session: run under `systemd-run --user --scope -p Delegate=yes`".to_string(),
        )
    } else {
        (HealthStatus::Healthy, "Ok", String::new())
    };
    let cg = |s: S| s.on_host(host.cgroup_delegated, "no delegated cgroup in this session");
    let gpu = |s: S| {
        s.on_host(
            host.nvidia_ctk,
            "nvidia-ctk not installed: no CDI spec can exist",
        )
    };
    ProviderReport::build(
        "linux",
        ProviderKind::Compute,
        true,
        ProviderHealth {
            status,
            reason,
            message,
        },
        |c| {
            match c {
        C::ProviderAvailability => S::Partial { detail: "the kernel is always there; what varies is rootless, subuid and cgroup delegation — each probed separately" },
        C::ResourceReadback => S::Supported { evidence: "e2e:comandos de leitura (não destrutivos)" },
        C::Events => S::Partial { detail: "`system events` reads a persisted log the CLI writes on each action; no watch stream (`WatchEvents` unserved)" },
        C::AsyncOperations => S::NotImplemented,
        C::ContainerLifecycle => S::Supported { evidence: "e2e:container: ciclo de vida + hot reconfig" },
        C::ContainerExec => S::Supported { evidence: "check:container exec" },
        C::ContainerLogs => S::Supported { evidence: "check:container logs" },
        C::ContainerHotReconfigure => S::Supported { evidence: "check:update: mount visível DENTRO do container" },
        C::ContainerResourceLimits => cg(S::Supported { evidence: "e2e:limites: o que se declara é IMPOSTO, não só escrito" }),
        C::ContainerGpuCdi => gpu(S::Partial { detail: "consumes CDI specs generated by `nvidia-ctk`; never run on a GPU host in the battery" }),
        C::ContainerSeccompCustomProfile => S::Supported { evidence: "check:seccomp: a regra ERRNO continua a negar" },
        C::ContainerOomDetection => cg(S::Partial { detail: "`Dead (OOMKilled)` from `memory.events.local`, read by the supervisor; `scen_oom` kills but does not assert the reason yet" }),
        C::PodSharedNetwork => S::Supported { evidence: "chaos:scen_pod_namespace_isolation" },
        C::PodSharedIpcUts => S::Partial { detail: "members `setns` into the first member's ipc/uts; no battery check reads them" },
        C::PodSharedPid => S::NotImplemented,
        C::ContainerImages => S::Supported { evidence: "e2e:image" },
        C::ContainerBackupRestore => S::Supported { evidence: "check:backup restore --force pára, repõe e arranca" },
        C::VmCreate | C::VmStart | C::VmStop | C::VmDestroy | C::VmRestart | C::VmPause
        | C::VmResume | C::VmResumeSameIdentity | C::VmClone | C::VmTemplate | C::VmResizeCold
        | C::VmHotplug | C::VmExtraDisks | C::VmExtraNics | C::VmDiskResize | C::VmPciPassthrough
        | C::VmTpm | C::VmCpuModel | C::VmCpuPinning | C::VmHugepages | C::VmCloudInit
        | C::VmRestartPolicyNative | C::VmNamespaceIsolation | C::VmAntispoof | C::VmRawDefinition
        | C::VmNetworkNat | C::VmNetworkBridge | C::VmNetworkSdn | C::VmStaticIp | C::StoragePools
        | C::VmSnapshotDisk | C::VmSnapshotMemory | C::VmSnapshotRestore | C::VmSnapshotDelete
        | C::VmSnapshotPersistent | C::VmBackupDisk | C::VmBackupQuiesced | C::VmBackupRestore
        | C::VmMigrationCold | C::VmMigrationLive | C::VmReplication | C::VmHighAvailability
        | C::VmConsoleSerial | C::VmConsoleVnc | C::VmGuestAgent | C::VmIpObserved => {
            S::UnsupportedByProvider { reason: "a container provider; VMs are libvirt's, Cloud Hypervisor's or Proxmox's" }
        }
        C::MetricsPrometheus => S::Partial { detail: "`/metrics` on the CRI and management sockets; per-container gauges, no battery scrape" },
        C::MetricsPerWorkloadNetwork => S::Partial { detail: "rx/tx per container read in its netns by the dashboard collector; not exported per container" },
        C::HostHealth => S::Supported { evidence: "check:system info" },
        C::HostCapacity => S::NotImplemented,
        C::TransportVerified => S::Partial { detail: "unix sockets with SO_PEERCRED (CRI, management, docker-api); no TCP is ever bound" },
        C::CredentialInVault => S::Partial { detail: "`--secret` values are resolved from the vault at spawn and never persisted in the record" },
        C::NetBridge | C::NetMacvlanIpvlan | C::NetVlan | C::NetOverlayVxlan | C::NetOverlayEncrypted
        | C::NetIpam | C::NetStaticIp | C::NetDns | C::NetPublishPorts | C::NetRoutesBetweenNetworks
        | C::NetNamespaceIsolation | C::NetL7Proxy | C::NetTunnelEgress | C::NetIpv6 | C::NetRateLimit
        | C::NetPacketCapture | C::FirewallPerWorkload | C::FirewallDefaultDeny
        | C::FirewallSourceFiltering | C::FirewallEgressPolicy | C::VolumeLocal | C::VolumeBind
        | C::VolumeNfs | C::VolumeCifs | C::VolumeWebdav | C::VolumeQuota | C::VolumeSnapshot
        | C::VolumeProvisionNas | C::StorageLvmThin | C::StorageZfsBtrfs | C::StorageCeph => {
            S::UnsupportedByProvider { reason: "not a compute capability: answered by the network/storage provider" }
        }
    }
        },
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn without_delegation_limits_read_as_unavailable_not_as_supported() {
        let host = LinuxHost {
            cgroup_delegated: false,
            ..LinuxHost::ASSUMED
        };
        let r = report(&host);
        assert_eq!(r.health.reason, "CgroupNotDelegated");
        let lim = r
            .capabilities
            .iter()
            .find(|x| x.capability == C::ContainerResourceLimits)
            .unwrap();
        assert_eq!(lim.state.label(), "unavailable-on-host");
        let exec = r
            .capabilities
            .iter()
            .find(|x| x.capability == C::ContainerExec)
            .unwrap();
        assert_eq!(exec.state.label(), "supported");
    }
}
