sonar.projectKey=__NAME__
sonar.projectName=__NAME__
sonar.sources=config,core,notes,webhooks,gunicorn.conf.py,manage.py
sonar.exclusions=**/migrations/**
sonar.tests=tests
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8
