sonar.projectKey=__NAME__
sonar.projectName=__NAME__
sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.sourceEncoding=UTF-8
# `go test -coverprofile=coverage.out ./...` before a Sonar scan, if you want coverage reported.
sonar.go.coverage.reportPaths=coverage.out
