# lab-samba — autenticacao e partilha de ficheiros
apiVersion: delonix.io/v1
kind: Vm
metadata:
  name: lab-samba
spec:
  disk: delonix-vm-base:ubuntu-24.04
  vcpus: 1
  memory: 1G
  backend: libvirt
  netMode: nat
  userData: ./cloud-init/samba.yaml
  extraNics:
    - type: network
      source: labnet
      model: virtio
      mac: "52:54:00:5a:b0:12"
