# lab-cli — posto de trabalho: recebe endereco do DHCP e autentica no Samba
apiVersion: delonix.io/v1
kind: Vm
metadata:
  name: lab-cli
spec:
  disk: DISK_PLACEHOLDER
  vcpus: 1
  memory: 1G
  backend: libvirt
  netMode: nat
  userData: ./cloud-init/cliente.yaml
  extraNics:
    - type: network
      source: labnet
      model: virtio
      mac: "52:54:00:5a:b0:13"
