//! Embeds the project templates (`templates/<name>/…`) into the binary so
//! `delonix … init --template <name>` scaffolds a complete project with no
//! filesystem dependency. Each file is embedded via `include_str!` (content
//! stays out of the generated file); the scaffolder substitutes the `__NAME__`
//! / `__MODULE__` / `__PORT__` tokens at write time. New templates = a new
//! directory under `templates/`; no code change needed.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo::rerun-if-changed=templates");
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("templates");
    let mut out = String::from("// @generated by build.rs — do not edit.\npub static TEMPLATES: &[(&str, &[(&str, &str)])] = &[\n");
    // Per-template metadata (exposed port + health path + default version,
    // `""` if the template has none) for `--up` and `-v`.
    let mut meta = String::from("pub static TEMPLATE_META: &[(&str, &str, &str, &str)] = &[\n");

    let mut names: Vec<PathBuf> = std::fs::read_dir(&root)
        .map(|rd| {
            rd.flatten()
                .map(|e| e.path())
                .filter(|p| p.is_dir())
                .collect()
        })
        .unwrap_or_default();
    names.sort();

    for tdir in &names {
        let name = tdir.file_name().unwrap().to_string_lossy();
        // `template.meta` (optional): `port=…` / `health=…` / `version=…`. It is
        // NOT written into the project — it only feeds `--up` and the
        // `__TEMPLATE_VERSION__` substitution. Default: 8000 + the apps' health
        // + no version (a template without `version=` never uses the token,
        // and `-v` is refused on it).
        let (mut port, mut health, mut version) = (
            "8000".to_string(),
            "/api/v1/health/live".to_string(),
            String::new(),
        );
        if let Ok(txt) = std::fs::read_to_string(tdir.join("template.meta")) {
            for line in txt.lines() {
                if let Some(v) = line.trim().strip_prefix("port=") {
                    port = v.trim().to_string();
                } else if let Some(v) = line.trim().strip_prefix("health=") {
                    health = v.trim().to_string();
                } else if let Some(v) = line.trim().strip_prefix("version=") {
                    version = v.trim().to_string();
                }
            }
        }
        writeln!(meta, "    ({name:?}, {port:?}, {health:?}, {version:?}),").unwrap();

        writeln!(out, "    ({name:?}, &[").unwrap();
        let mut files = Vec::new();
        collect(tdir, tdir, &mut files);
        files.retain(|(rel, _)| rel != "template.meta"); // meta não vai no projecto
        files.sort();
        for (rel, abs) in files {
            // include_str! wants a path relative to THIS file (build.rs) or
            // absolute; use absolute so it works regardless of OUT_DIR.
            writeln!(
                out,
                "        ({:?}, include_str!({:?})),",
                rel,
                abs.to_string_lossy()
            )
            .unwrap();
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");
    meta.push_str("];\n");
    out.push_str(&meta);

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("templates.rs");
    std::fs::write(dest, out).unwrap();

    // Metadados de build para o `--version` rico: hash git curto + data UTC.
    // Sem dependências — shell-out com fallbacks (um build de tarball sem .git
    // continua a compilar). SOURCE_DATE_EPOCH respeitado (builds reprodutíveis).
    let hash = std::process::Command::new("git")
        .args(["rev-parse", "--short=9", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|| "unknown".into());
    let date = std::process::Command::new("date")
        .args(["-u", "+%Y-%m-%d"])
        .env_remove("TZ")
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|| "unknown".into());
    // Distance from the newest tag this commit contains. The workspace version
    // stays EQUAL to that tag between releases (scripts/version_gate.py), so on
    // its own the number cannot tell a release build from one 45 commits later —
    // measured: a build from main answered `delonix 3.1.0` while carrying work
    // no release had shipped. Empty at the tag itself and without git.
    let since = std::process::Command::new("git")
        .args(["describe", "--tags", "--long", "--match", "v[0-9]*"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .and_then(|d| {
            // `v3.1.0-45-g45219046`: the tag may itself contain `-`, so split
            // from the right.
            let mut parts = d.rsplitn(3, '-');
            let _hash = parts.next()?;
            let count = parts.next()?;
            let tag = parts.next()?;
            (count != "0").then(|| format!("{count}|{tag}"))
        })
        .unwrap_or_default();
    println!("cargo:rustc-env=DELONIX_GIT_HASH={hash}");
    println!("cargo:rustc-env=DELONIX_GIT_SINCE={since}");
    println!("cargo:rustc-env=DELONIX_BUILD_DATE={date}");
    // Re-corre quando o HEAD muda — sem isto o hash fossiliza entre commits.
    println!("cargo::rerun-if-changed=../../.git/HEAD");
    // A new tag changes the distance without moving HEAD.
    println!("cargo::rerun-if-changed=../../.git/refs/tags");
    println!("cargo::rerun-if-changed=../../.git/packed-refs");
}

/// Collect `(relative-path, absolute-path)` of every file under `dir`.
fn collect(base: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(rd) = std::fs::read_dir(dir) else {
        return;
    };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect(base, &p, out);
        } else if let Ok(rel) = p.strip_prefix(base) {
            out.push((rel.to_string_lossy().replace('\\', "/"), p.clone()));
        }
    }
}
