//! Embeds the project templates (`templates/<name>/…`) into the binary so
//! `delonix … init --template <name>` scaffolds a complete project with no
//! filesystem dependency. Each file is embedded via `include_str!` (content
//! stays out of the generated file); the scaffolder substitutes the `__NAME__`
//! / `__MODULE__` / `__PORT__` tokens at write time. New templates = a new
//! directory under `templates/`; no code change needed.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo::rerun-if-changed=templates");
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("templates");
    let mut out = String::from("// @generated by build.rs — do not edit.\npub static TEMPLATES: &[(&str, &[(&str, &str)])] = &[\n");

    let mut names: Vec<PathBuf> = std::fs::read_dir(&root)
        .map(|rd| rd.flatten().map(|e| e.path()).filter(|p| p.is_dir()).collect())
        .unwrap_or_default();
    names.sort();

    for tdir in &names {
        let name = tdir.file_name().unwrap().to_string_lossy();
        writeln!(out, "    ({name:?}, &[").unwrap();
        let mut files = Vec::new();
        collect(tdir, tdir, &mut files);
        files.sort();
        for (rel, abs) in files {
            // include_str! wants a path relative to THIS file (build.rs) or
            // absolute; use absolute so it works regardless of OUT_DIR.
            writeln!(out, "        ({:?}, include_str!({:?})),", rel, abs.to_string_lossy()).unwrap();
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("templates.rs");
    std::fs::write(dest, out).unwrap();
}

/// Collect `(relative-path, absolute-path)` of every file under `dir`.
fn collect(base: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect(base, &p, out);
        } else if let Ok(rel) = p.strip_prefix(base) {
            out.push((rel.to_string_lossy().replace('\\', "/"), p.clone()));
        }
    }
}
