//! Embeds the project templates (`templates/<name>/…`) into the binary so
//! `delonix … init --template <name>` scaffolds a complete project with no
//! filesystem dependency. Each file is embedded via `include_str!` (content
//! stays out of the generated file); the scaffolder substitutes the `__NAME__`
//! / `__MODULE__` / `__PORT__` tokens at write time. New templates = a new
//! directory under `templates/`; no code change needed.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo::rerun-if-changed=templates");
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("templates");
    let mut out = String::from("// @generated by build.rs — do not edit.\npub static TEMPLATES: &[(&str, &[(&str, &str)])] = &[\n");
    // Metadados por template (porta exposta + path do health), para o `--up`.
    let mut meta = String::from("pub static TEMPLATE_META: &[(&str, &str, &str)] = &[\n");

    let mut names: Vec<PathBuf> = std::fs::read_dir(&root)
        .map(|rd| {
            rd.flatten()
                .map(|e| e.path())
                .filter(|p| p.is_dir())
                .collect()
        })
        .unwrap_or_default();
    names.sort();

    for tdir in &names {
        let name = tdir.file_name().unwrap().to_string_lossy();
        // `template.meta` (opcional): `port=…` / `health=…`. NÃO é escrito no
        // projecto — só alimenta o `--up`. Default: 8000 + o health das apps.
        let (mut port, mut health) = ("8000".to_string(), "/api/v1/health/live".to_string());
        if let Ok(txt) = std::fs::read_to_string(tdir.join("template.meta")) {
            for line in txt.lines() {
                if let Some(v) = line.trim().strip_prefix("port=") {
                    port = v.trim().to_string();
                } else if let Some(v) = line.trim().strip_prefix("health=") {
                    health = v.trim().to_string();
                }
            }
        }
        writeln!(meta, "    ({name:?}, {port:?}, {health:?}),").unwrap();

        writeln!(out, "    ({name:?}, &[").unwrap();
        let mut files = Vec::new();
        collect(tdir, tdir, &mut files);
        files.retain(|(rel, _)| rel != "template.meta"); // meta não vai no projecto
        files.sort();
        for (rel, abs) in files {
            // include_str! wants a path relative to THIS file (build.rs) or
            // absolute; use absolute so it works regardless of OUT_DIR.
            writeln!(
                out,
                "        ({:?}, include_str!({:?})),",
                rel,
                abs.to_string_lossy()
            )
            .unwrap();
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");
    meta.push_str("];\n");
    out.push_str(&meta);

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("templates.rs");
    std::fs::write(dest, out).unwrap();

    // Metadados de build para o `--version` rico: hash git curto + data UTC.
    // Sem dependências — shell-out com fallbacks (um build de tarball sem .git
    // continua a compilar). SOURCE_DATE_EPOCH respeitado (builds reprodutíveis).
    let hash = std::process::Command::new("git")
        .args(["rev-parse", "--short=9", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|| "unknown".into());
    let date = std::process::Command::new("date")
        .args(["-u", "+%Y-%m-%d"])
        .env_remove("TZ")
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_else(|| "unknown".into());
    println!("cargo:rustc-env=DELONIX_GIT_HASH={hash}");
    println!("cargo:rustc-env=DELONIX_BUILD_DATE={date}");
    // Re-corre quando o HEAD muda — sem isto o hash fossiliza entre commits.
    println!("cargo::rerun-if-changed=../../.git/HEAD");
}

/// Collect `(relative-path, absolute-path)` of every file under `dir`.
fn collect(base: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(rd) = std::fs::read_dir(dir) else {
        return;
    };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect(base, &p, out);
        } else if let Ok(rel) = p.strip_prefix(base) {
            out.push((rel.to_string_lossy().replace('\\', "/"), p.clone()));
        }
    }
}
