"""__NAME__ — a FastAPI service generated by `delonix init -t fastapi`."""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("__NAME__")
except PackageNotFoundError:  # running from a source tree that is not installed
    __version__ = "0.0.0"
