//! CDI (Container Device Interface, `cdi.k8s.io`/CNCF) **consumer** — parses
//! specs already generated by `nvidia-ctk cdi generate` (or an equivalent
//! vendor tool) and translates their `ContainerEdit`s into the exact same
//! `Vec<Mount>`/`Vec<String>` device specs/env that `-v`/`--device` already
//! feed into `bind_volume`/`bind_devices` (`crates/delonix-runtime/src/
//! lib.rs`). Deliberately NOT a driver-discovery/`nvidia-container-cli`
//! shell-out: this repo's bind mounts are always performed by the
//! container's OWN already-namespaced init, before its `pivot_root` — never
//! a second process `setns`-ing into a target by PID (the legacy NVIDIA hook
//! model), which would reintroduce exactly the cross-namespace privilege
//! problem the `--net <rede>` re-exec trick was built to avoid. Driver
//! discovery/versioning stays 100% inside `nvidia-ctk`, same as every other
//! container engine (Docker/Podman/containerd/CRI-O) — none of them
//! reimplement it either.
//!
//! Scope (v1): NVIDIA-shaped specs consumed generically (any CDI-conformant
//! vendor spec parses the same way); `hooks` (the OCI-hook-stdin-state
//! `createContainer` protocol real specs declare) are NOT executed — a
//! best-effort `ldconfig -r <rootfs>` after the mount/device loop
//! (`setup_rootfs`, still pre-`pivot_root`) is used instead, and any spec
//! that DOES declare hooks gets a clear (non-fatal) warning that they were
//! skipped, so the gap is visible rather than silently assumed harmless.

use std::path::{Path, PathBuf};

use delonix_runtime_core::{Error, Mount, Result};
use serde::Deserialize;

/// A parsed CDI spec (`cdi.k8s.io/v0.x.x` — only the fields this consumer
/// needs; unknown fields are ignored, matching every other `serde` parser in
/// this codebase — a spec MAY have `containerEdits/hooks` at the top level
/// too (device-independent edits), but no real NVIDIA spec observed puts
/// anything load-bearing there, so v1 only reads per-device edits).
#[derive(Debug, Deserialize)]
struct CdiSpec {
    kind: String,
    #[serde(default)]
    devices: Vec<CdiDevice>,
}

#[derive(Debug, Deserialize)]
struct CdiDevice {
    name: String,
    #[serde(rename = "containerEdits", default)]
    container_edits: ContainerEdits,
}

#[derive(Debug, Default, Deserialize)]
struct ContainerEdits {
    #[serde(rename = "deviceNodes", default)]
    device_nodes: Vec<CdiDeviceNode>,
    #[serde(default)]
    mounts: Vec<CdiMount>,
    #[serde(default)]
    env: Vec<String>,
    #[serde(default)]
    hooks: Vec<serde_json::Value>,
}

#[derive(Debug, Deserialize)]
struct CdiDeviceNode {
    path: String,
    #[serde(rename = "hostPath", default)]
    host_path: Option<String>,
}

#[derive(Debug, Deserialize)]
struct CdiMount {
    #[serde(rename = "hostPath")]
    host_path: String,
    #[serde(rename = "containerPath")]
    container_path: String,
    #[serde(default)]
    options: Vec<String>,
}

/// What a resolved CDI device (or the synthesized `=all`) contributes to a
/// container being created — already in the shape `cmd_run` needs.
#[derive(Debug, Default)]
pub(crate) struct CdiEdits {
    /// `host[:container]` — same format `bind_devices`/`--device` already parse.
    pub devices: Vec<String>,
    pub mounts: Vec<Mount>,
    pub env: Vec<String>,
    /// `true` if any resolved device declared `hooks` this consumer doesn't
    /// execute — surfaced as a one-line warning, never silent.
    pub had_unexecuted_hooks: bool,
}

/// `true` if `spec` has the `vendor.com/class=name` shape a CDI-qualified
/// device name always does (Docker's own disambiguation rule, reused
/// verbatim rather than inventing a delonix-specific one) — as opposed to a
/// plain host device path (`/dev/foo` or `/dev/foo:/dev/bar`), which never
/// starts with a non-`/` vendor segment containing a dot before the `/`.
pub(crate) fn is_cdi_qualified(spec: &str) -> bool {
    let Some((vendor_class, name)) = spec.split_once('=') else {
        return false;
    };
    !name.is_empty() && vendor_class.contains('.') && vendor_class.contains('/')
}

/// `/etc/cdi` (static, lower precedence) then `/var/run/cdi` (dynamic,
/// generated per-boot, higher precedence) — CDI spec directories, scanned in
/// that order so a later match can override an earlier one with the same
/// device name (mirrors the spec's own documented precedence).
fn cdi_spec_dirs() -> [&'static Path; 2] {
    [Path::new("/etc/cdi"), Path::new("/var/run/cdi")]
}

fn discover_cdi_specs() -> Vec<PathBuf> {
    let mut out = Vec::new();
    for dir in cdi_spec_dirs() {
        let Ok(rd) = std::fs::read_dir(dir) else {
            continue;
        };
        for entry in rd.flatten() {
            let path = entry.path();
            let is_spec = path
                .extension()
                .and_then(|e| e.to_str())
                .is_some_and(|e| matches!(e, "json" | "yaml" | "yml"));
            if is_spec {
                out.push(path);
            }
        }
    }
    out
}

/// `true` if a CDI spec is available on this host, OR `nvidia-ctk` is on
/// `PATH` (able to generate one) — the fast, no-parsing check
/// `ensure_cdi_available` uses before failing a `--gpus nvidia`/CDI request.
fn cdi_usable() -> bool {
    !discover_cdi_specs().is_empty() || which("nvidia-ctk")
}

fn which(bin: &str) -> bool {
    std::env::var_os("PATH")
        .map(|paths| std::env::split_paths(&paths).any(|dir| dir.join(bin).is_file()))
        .unwrap_or(false)
}

/// Hard, upfront, actionable gate — called BEFORE any container/rootfs work
/// starts (same point ports are pre-validated at). Never a silent fallback
/// to the raw `/dev/nvidia*` glob: without the real driver libraries
/// injected, CUDA/cuDNN fails at runtime with a confusing dlopen error, not
/// a clear one.
pub(crate) fn ensure_cdi_available() -> Result<()> {
    if cdi_usable() {
        return Ok(());
    }
    Err(Error::Invalid(
        "--gpus nvidia (or a nvidia.com/gpu=... --device) requested but no CDI spec was found \
         (checked /etc/cdi/*.json|yaml, /var/run/cdi/*.json|yaml) and `nvidia-ctk` is not on \
         PATH.\n\nWithout this, the container would only get the raw /dev/nvidia* nodes — \
         CUDA/cuDNN would fail to load at runtime with a confusing error, not a clear one.\n\n\
         Install nvidia-container-toolkit and generate the CDI spec, then retry:\n  \
         sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml"
            .into(),
    ))
}

/// Resolves one CDI-qualified device name (`nvidia.com/gpu=0`, or the
/// synthesized aggregate `nvidia.com/gpu=all`) against every discovered
/// spec, merging its `deviceNodes`/`mounts`/`env` into `out`. `=all` merges
/// EVERY device this vendor/class declares (not a separate spec-level
/// entry — real CDI specs synthesize `=all` as just another `devices[]`
/// entry, but resolving it generically here doesn't depend on that).
pub(crate) fn resolve_cdi_device(qualified_name: &str, out: &mut CdiEdits) -> Result<()> {
    let (vendor_class, name) = qualified_name.split_once('=').ok_or_else(|| {
        Error::Invalid(format!(
            "invalid CDI device name: '{qualified_name}' (expected vendor.com/class=name)"
        ))
    })?;
    let specs = discover_cdi_specs();
    if specs.is_empty() {
        return Err(Error::Invalid(format!(
            "'{qualified_name}': no CDI spec found (checked /etc/cdi, /var/run/cdi)"
        )));
    }
    let mut found = false;
    for path in &specs {
        let Ok(text) = std::fs::read_to_string(path) else {
            continue;
        };
        let spec: std::result::Result<CdiSpec, _> =
            if path.extension().and_then(|e| e.to_str()) == Some("json") {
                serde_json::from_str(&text).map_err(|e| e.to_string())
            } else {
                serde_yaml::from_str(&text).map_err(|e| e.to_string())
            };
        let Ok(spec) = spec else { continue };
        if !spec.kind.starts_with(vendor_class) && spec.kind != vendor_class {
            continue;
        }
        for device in &spec.devices {
            if name == "all" || device.name == name {
                apply_edits(&device.container_edits, out);
                found = true;
            }
        }
    }
    if !found {
        return Err(Error::Invalid(format!(
            "'{qualified_name}': not found in any discovered CDI spec"
        )));
    }
    Ok(())
}

fn apply_edits(edits: &ContainerEdits, out: &mut CdiEdits) {
    for node in &edits.device_nodes {
        let host = node.host_path.as_deref().unwrap_or(&node.path);
        out.devices.push(format!("{host}:{}", node.path));
    }
    for m in &edits.mounts {
        out.mounts.push(Mount {
            source: m.host_path.clone(),
            target: m.container_path.clone(),
            readonly: m.options.iter().any(|o| o == "ro"),
        });
    }
    out.env.extend(edits.env.iter().cloned());
    if !edits.hooks.is_empty() {
        out.had_unexecuted_hooks = true;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_cdi_qualified_distingue_de_um_caminho_de_dev() {
        assert!(is_cdi_qualified("nvidia.com/gpu=all"));
        assert!(is_cdi_qualified("nvidia.com/gpu=0"));
        assert!(!is_cdi_qualified("/dev/nvidia0"));
        assert!(!is_cdi_qualified("/dev/nvidia0:/dev/nvidia0"));
        assert!(!is_cdi_qualified("nvidia.com/gpu")); // no '='
        assert!(!is_cdi_qualified("gpu=all")); // no dot/slash vendor
    }

    #[test]
    fn resolve_cdi_device_parses_um_spec_json_de_exemplo() {
        let dir = std::env::temp_dir().join(format!(
            "delonix-cdi-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let spec = serde_json::json!({
            "cdiVersion": "0.6.0",
            "kind": "nvidia.com/gpu",
            "devices": [{
                "name": "0",
                "containerEdits": {
                    "deviceNodes": [{"path": "/dev/nvidia0"}],
                    "mounts": [{
                        "hostPath": "/usr/lib/x86_64-linux-gnu/libcuda.so.1",
                        "containerPath": "/usr/lib/x86_64-linux-gnu/libcuda.so.1",
                        "options": ["ro", "nosuid", "nodev", "bind"]
                    }],
                    "env": ["NVIDIA_VISIBLE_DEVICES=0"]
                }
            }]
        });
        std::fs::write(dir.join("nvidia.json"), spec.to_string()).unwrap();

        // Point discovery at our tmpdir by testing resolution logic directly
        // against a spec parsed from that exact path (discover_cdi_specs()
        // itself only scans the real /etc/cdi, /var/run/cdi — this test
        // exercises the parse+apply path, not host discovery).
        let text = std::fs::read_to_string(dir.join("nvidia.json")).unwrap();
        let parsed: CdiSpec = serde_json::from_str(&text).unwrap();
        assert_eq!(parsed.kind, "nvidia.com/gpu");
        let mut out = CdiEdits::default();
        apply_edits(&parsed.devices[0].container_edits, &mut out);
        assert_eq!(out.devices, vec!["/dev/nvidia0:/dev/nvidia0"]);
        assert_eq!(out.mounts.len(), 1);
        assert!(out.mounts[0].readonly);
        assert_eq!(out.env, vec!["NVIDIA_VISIBLE_DEVICES=0"]);
        assert!(!out.had_unexecuted_hooks);

        std::fs::remove_dir_all(&dir).ok();
    }
}
