//! CDI (Container Device Interface, `cdi.k8s.io`/CNCF) **consumer** — parses
//! specs already generated by `nvidia-ctk cdi generate` (or an equivalent
//! vendor tool) and translates their `ContainerEdit`s into the exact same
//! `Vec<Mount>`/`Vec<String>` device specs/env that `-v`/`--device` already
//! feed into `bind_volume`/`bind_devices` (`crates/delonix-runtime/src/
//! lib.rs`). Deliberately NOT a driver-discovery/`nvidia-container-cli`
//! shell-out: this repo's bind mounts are always performed by the
//! container's OWN already-namespaced init, before its `pivot_root` — never
//! a second process `setns`-ing into a target by PID (the legacy NVIDIA hook
//! model), which would reintroduce exactly the cross-namespace privilege
//! problem the `--net <rede>` re-exec trick was built to avoid. Driver
//! discovery/versioning stays 100% inside `nvidia-ctk`, same as every other
//! container engine (Docker/Podman/containerd/CRI-O) — none of them
//! reimplement it either.
//!
//! Scope (v1): NVIDIA-shaped specs consumed generically (any CDI-conformant
//! vendor spec parses the same way); `hooks` (the OCI-hook-stdin-state
//! `createContainer` protocol real specs declare) are NOT executed — a
//! best-effort `ldconfig -r <rootfs>` after the mount/device loop
//! (`setup_rootfs`, still pre-`pivot_root`) is used instead, and any spec
//! that DOES declare hooks gets a clear (non-fatal) warning that they were
//! skipped, so the gap is visible rather than silently assumed harmless.

use std::path::{Path, PathBuf};

use delonix_runtime_core::{Error, Mount, Result};
use serde::Deserialize;

/// A parsed CDI spec (`cdi.k8s.io/v0.x.x` — only the fields this consumer
/// needs; unknown fields are ignored, matching every other `serde` parser in
/// this codebase).
///
/// The top-level `containerEdits` are the spec's **device-independent** edits,
/// and they are where every real NVIDIA spec puts the load-bearing part.
/// Measured against a spec generated by `nvidia-ctk` 1.20.0 (`cdiVersion
/// 0.7.0`, driver 580, RTX 5060): the per-device entries carry three device
/// nodes and ZERO mounts, while the top level carries `/dev/nvidiactl`,
/// `/dev/nvidia-uvm`, `/dev/nvidia-uvm-tools`, `/dev/nvidia-modeset` and 51
/// mounts — every driver library plus `nvidia-smi`. Reading only per-device
/// edits handed the container `/dev/nvidia0` and nothing else: `--gpus all`
/// exited 0 and no CUDA process could initialise (no `nvidiactl`, no
/// `nvidia-uvm`, no `libcuda.so`), which is exactly the confusing runtime
/// failure `ensure_cdi_available` exists to prevent.
#[derive(Debug, Deserialize)]
struct CdiSpec {
    kind: String,
    #[serde(rename = "containerEdits", default)]
    container_edits: ContainerEdits,
    #[serde(default)]
    devices: Vec<CdiDevice>,
}

#[derive(Debug, Deserialize)]
struct CdiDevice {
    name: String,
    #[serde(rename = "containerEdits", default)]
    container_edits: ContainerEdits,
}

#[derive(Debug, Default, Deserialize)]
struct ContainerEdits {
    #[serde(rename = "deviceNodes", default)]
    device_nodes: Vec<CdiDeviceNode>,
    #[serde(default)]
    mounts: Vec<CdiMount>,
    #[serde(default)]
    env: Vec<String>,
    #[serde(default)]
    hooks: Vec<serde_json::Value>,
}

#[derive(Debug, Deserialize)]
struct CdiDeviceNode {
    path: String,
    #[serde(rename = "hostPath", default)]
    host_path: Option<String>,
}

#[derive(Debug, Deserialize)]
struct CdiMount {
    #[serde(rename = "hostPath")]
    host_path: String,
    #[serde(rename = "containerPath")]
    container_path: String,
    #[serde(default)]
    options: Vec<String>,
}

/// What a resolved CDI device (or the synthesized `=all`) contributes to a
/// container being created — already in the shape `cmd_run` needs.
#[derive(Debug, Default)]
pub(crate) struct CdiEdits {
    /// `host[:container]` — same format `bind_devices`/`--device` already parse.
    pub devices: Vec<String>,
    pub mounts: Vec<Mount>,
    pub env: Vec<String>,
    /// `true` if any resolved device declared `hooks` this consumer doesn't
    /// execute — surfaced as a one-line warning, never silent.
    pub had_unexecuted_hooks: bool,
}

/// `true` if `spec` has the `vendor.com/class=name` shape a CDI-qualified
/// device name always does (Docker's own disambiguation rule, reused
/// verbatim rather than inventing a delonix-specific one) — as opposed to a
/// plain host device path (`/dev/foo` or `/dev/foo:/dev/bar`), which never
/// starts with a non-`/` vendor segment containing a dot before the `/`.
pub(crate) fn is_cdi_qualified(spec: &str) -> bool {
    let Some((vendor_class, name)) = spec.split_once('=') else {
        return false;
    };
    !name.is_empty() && vendor_class.contains('.') && vendor_class.contains('/')
}

/// `/etc/cdi` (static, lower precedence) then `/var/run/cdi` (dynamic,
/// generated per-boot, higher precedence) — CDI spec directories, scanned in
/// that order so a later match can override an earlier one with the same
/// device name (mirrors the spec's own documented precedence).
fn cdi_spec_dirs() -> [&'static Path; 2] {
    [Path::new("/etc/cdi"), Path::new("/var/run/cdi")]
}

fn discover_cdi_specs() -> Vec<PathBuf> {
    let mut out = Vec::new();
    for dir in cdi_spec_dirs() {
        let Ok(rd) = std::fs::read_dir(dir) else {
            continue;
        };
        for entry in rd.flatten() {
            let path = entry.path();
            let is_spec = path
                .extension()
                .and_then(|e| e.to_str())
                .is_some_and(|e| matches!(e, "json" | "yaml" | "yml"));
            if is_spec {
                out.push(path);
            }
        }
    }
    out
}

/// `true` if `nvidia-ctk` is on `PATH` — i.e. the host CAN generate a spec but
/// has not. Used only to pick which half of the `ensure_cdi_available` message
/// to print: the two situations need different commands from the user.
fn can_generate_spec() -> bool {
    which("nvidia-ctk")
}

fn which(bin: &str) -> bool {
    std::env::var_os("PATH")
        .map(|paths| std::env::split_paths(&paths).any(|dir| dir.join(bin).is_file()))
        .unwrap_or(false)
}

/// Hard, upfront, actionable gate — called BEFORE any container/rootfs work
/// starts (same point ports are pre-validated at). Never a silent fallback
/// to the raw `/dev/nvidia*` glob: without the real driver libraries
/// injected, CUDA/cuDNN fails at runtime with a confusing dlopen error, not
/// a clear one.
pub(crate) fn ensure_cdi_available() -> Result<()> {
    if !discover_cdi_specs().is_empty() {
        return Ok(());
    }
    // A present `nvidia-ctk` used to satisfy this gate on its own. It must not:
    // the toolkit being installed says nothing about a spec having been
    // GENERATED, and the run then died further in with the terse
    // `'nvidia.com/gpu=all': no CDI spec found` — losing the one message that
    // tells the user which command to type.
    let head = "--gpus nvidia (or a nvidia.com/gpu=... --device) requested but no CDI spec was \
                found (checked /etc/cdi/*.json|yaml, /var/run/cdi/*.json|yaml).\n\nWithout \
                one, the container would only get the raw /dev/nvidia* nodes — no \
                /dev/nvidiactl, no /dev/nvidia-uvm and no driver libraries, so CUDA/cuDNN \
                fails to load at runtime with a confusing error instead of a clear one.\n\n";
    let fix = if can_generate_spec() {
        "`nvidia-ctk` IS installed — generate the spec and retry:\n  \
         sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml"
    } else {
        "Install nvidia-container-toolkit and generate the CDI spec, then retry:\n  \
         sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml"
    };
    Err(Error::Invalid(format!("{head}{fix}")))
}

/// Resolves one CDI-qualified device name (`nvidia.com/gpu=0`, or the
/// synthesized aggregate `nvidia.com/gpu=all`) against every discovered
/// spec, merging its `deviceNodes`/`mounts`/`env` into `out`. `=all` merges
/// EVERY device this vendor/class declares (not a separate spec-level
/// entry — real CDI specs synthesize `=all` as just another `devices[]`
/// entry, but resolving it generically here doesn't depend on that).
pub(crate) fn resolve_cdi_device(qualified_name: &str, out: &mut CdiEdits) -> Result<()> {
    resolve_cdi_device_in(&discover_cdi_specs(), qualified_name, out)
}

/// The body of `resolve_cdi_device`, against an explicit spec list — host
/// discovery is the caller's job so that tests can point this at a temporary
/// directory holding a real-shaped spec. Without the split the only testable
/// unit was `apply_edits`, which is precisely the function that was already
/// correct while the caller dropped the top-level edits on the floor.
fn resolve_cdi_device_in(
    specs: &[PathBuf],
    qualified_name: &str,
    out: &mut CdiEdits,
) -> Result<()> {
    let (vendor_class, name) = qualified_name.split_once('=').ok_or_else(|| {
        Error::Invalid(format!(
            "invalid CDI device name: '{qualified_name}' (expected vendor.com/class=name)"
        ))
    })?;
    if specs.is_empty() {
        return Err(Error::Invalid(format!(
            "'{qualified_name}': no CDI spec found (checked /etc/cdi, /var/run/cdi)"
        )));
    }
    let mut found = false;
    for path in specs {
        let Ok(text) = std::fs::read_to_string(path) else {
            continue;
        };
        let spec: std::result::Result<CdiSpec, _> =
            if path.extension().and_then(|e| e.to_str()) == Some("json") {
                serde_json::from_str(&text).map_err(|e| e.to_string())
            } else {
                serde_yaml::from_str(&text).map_err(|e| e.to_string())
            };
        let Ok(spec) = spec else { continue };
        if !spec.kind.starts_with(vendor_class) && spec.kind != vendor_class {
            continue;
        }
        let mut spec_contributed = false;
        for device in &spec.devices {
            if name == "all" || device.name == name {
                apply_edits(&device.container_edits, out);
                spec_contributed = true;
                found = true;
            }
        }
        // Device-independent edits, applied ONCE per spec that contributed a
        // device — never per device, or a `=all` that matches three entries
        // would bind the same 51 mounts three times.
        if spec_contributed {
            apply_edits(&spec.container_edits, out);
        }
    }
    out.dedupe();
    if !found {
        return Err(Error::Invalid(format!(
            "'{qualified_name}': not found in any discovered CDI spec"
        )));
    }
    Ok(())
}

impl CdiEdits {
    /// Drops repeated device nodes/mounts/env, first occurrence wins.
    ///
    /// `=all` legitimately matches several `devices[]` entries that repeat the
    /// same node: `nvidia-ctk` emits `0`, the `GPU-<uuid>` alias and `all`,
    /// each declaring the identical `/dev/nvidia0`, `/dev/dri/card1`,
    /// `/dev/dri/renderD128`. Two discovered spec directories can also declare
    /// the same host mount (`/etc/cdi` and `/var/run/cdi` are both scanned by
    /// design). Binding the same path three times is wasted work at best and an
    /// EBUSY at worst, so the merged result is deduplicated once, here, rather
    /// than in each consumer of `CdiEdits`.
    fn dedupe(&mut self) {
        let mut seen = std::collections::HashSet::new();
        self.devices.retain(|d| seen.insert(d.clone()));
        let mut seen_env = std::collections::HashSet::new();
        self.env.retain(|e| seen_env.insert(e.clone()));
        let mut seen_mounts = std::collections::HashSet::new();
        self.mounts
            .retain(|m| seen_mounts.insert((m.source.clone(), m.target.clone(), m.readonly)));
    }
}

fn apply_edits(edits: &ContainerEdits, out: &mut CdiEdits) {
    for node in &edits.device_nodes {
        let host = node.host_path.as_deref().unwrap_or(&node.path);
        out.devices.push(format!("{host}:{}", node.path));
    }
    for m in &edits.mounts {
        out.mounts.push(Mount {
            source: m.host_path.clone(),
            target: m.container_path.clone(),
            readonly: m.options.iter().any(|o| o == "ro"),
            propagation: None,
            // A CDI spec describes the HOST; parts of it do not fit an
            // arbitrary image, and one of those must not sink the container.
            optional: true,
        });
    }
    out.env.extend(edits.env.iter().cloned());
    if !edits.hooks.is_empty() {
        out.had_unexecuted_hooks = true;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn is_cdi_qualified_distingue_de_um_caminho_de_dev() {
        assert!(is_cdi_qualified("nvidia.com/gpu=all"));
        assert!(is_cdi_qualified("nvidia.com/gpu=0"));
        assert!(!is_cdi_qualified("/dev/nvidia0"));
        assert!(!is_cdi_qualified("/dev/nvidia0:/dev/nvidia0"));
        assert!(!is_cdi_qualified("nvidia.com/gpu")); // no '='
        assert!(!is_cdi_qualified("gpu=all")); // no dot/slash vendor
    }

    #[test]
    fn resolve_cdi_device_parses_um_spec_json_de_exemplo() {
        let dir = std::env::temp_dir().join(format!(
            "delonix-cdi-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let spec = serde_json::json!({
            "cdiVersion": "0.6.0",
            "kind": "nvidia.com/gpu",
            "devices": [{
                "name": "0",
                "containerEdits": {
                    "deviceNodes": [{"path": "/dev/nvidia0"}],
                    "mounts": [{
                        "hostPath": "/usr/lib/x86_64-linux-gnu/libcuda.so.1",
                        "containerPath": "/usr/lib/x86_64-linux-gnu/libcuda.so.1",
                        "options": ["ro", "nosuid", "nodev", "bind"]
                    }],
                    "env": ["NVIDIA_VISIBLE_DEVICES=0"]
                }
            }]
        });
        std::fs::write(dir.join("nvidia.json"), spec.to_string()).unwrap();

        // Point discovery at our tmpdir by testing resolution logic directly
        // against a spec parsed from that exact path (discover_cdi_specs()
        // itself only scans the real /etc/cdi, /var/run/cdi — this test
        // exercises the parse+apply path, not host discovery).
        let text = std::fs::read_to_string(dir.join("nvidia.json")).unwrap();
        let parsed: CdiSpec = serde_json::from_str(&text).unwrap();
        assert_eq!(parsed.kind, "nvidia.com/gpu");
        let mut out = CdiEdits::default();
        apply_edits(&parsed.devices[0].container_edits, &mut out);
        assert_eq!(out.devices, vec!["/dev/nvidia0:/dev/nvidia0"]);
        assert_eq!(out.mounts.len(), 1);
        assert!(out.mounts[0].readonly);
        assert_eq!(out.env, vec!["NVIDIA_VISIBLE_DEVICES=0"]);
        assert!(!out.had_unexecuted_hooks);

        std::fs::remove_dir_all(&dir).ok();
    }

    /// Writes a spec shaped like the one `nvidia-ctk` 1.20.0 actually emits —
    /// everything load-bearing at the TOP level, per-device entries carrying
    /// only the numbered nodes, and `=all` repeated across three device names.
    fn spec_with_the_real_nvidia_shape(dir: &Path) {
        let nodes = |extra: &str| {
            serde_json::json!([
                {"path": "/dev/nvidia0"},
                {"path": format!("/dev/dri/{extra}")},
                {"path": "/dev/dri/renderD128"}
            ])
        };
        let spec = serde_json::json!({
            "cdiVersion": "0.7.0",
            "kind": "nvidia.com/gpu",
            "containerEdits": {
                "deviceNodes": [
                    {"path": "/dev/nvidia-modeset"},
                    {"path": "/dev/nvidia-uvm"},
                    {"path": "/dev/nvidia-uvm-tools"},
                    {"path": "/dev/nvidiactl"}
                ],
                "mounts": [
                    {"hostPath": "/usr/bin/nvidia-smi",
                     "containerPath": "/usr/bin/nvidia-smi",
                     "options": ["ro", "nosuid", "nodev", "bind"]},
                    {"hostPath": "/usr/lib/x86_64-linux-gnu/libcuda.so.580.173.02",
                     "containerPath": "/usr/lib/x86_64-linux-gnu/libcuda.so.580.173.02",
                     "options": ["ro", "nosuid", "nodev", "bind"]}
                ],
                "env": ["NVIDIA_VISIBLE_DEVICES=void"],
                "hooks": [{"hookName": "createContainer", "path": "/usr/bin/nvidia-ctk"}]
            },
            "devices": [
                {"name": "0", "containerEdits": {"deviceNodes": nodes("card1")}},
                {"name": "GPU-586a446c", "containerEdits": {"deviceNodes": nodes("card1")}},
                {"name": "all", "containerEdits": {"deviceNodes": nodes("card1")}}
            ]
        });
        std::fs::write(dir.join("nvidia.json"), spec.to_string()).unwrap();
    }

    fn tmpdir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "delonix-cdi-{tag}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn resolve_all_brings_top_level_edits_not_just_dev_nvidia0() {
        // The regression this file was written to fix: with only per-device
        // edits, `--gpus all` injected /dev/nvidia0 and NOTHING else — no
        // control device, no uvm, no libcuda, no nvidia-smi — and exited 0.
        let dir = tmpdir("topo");
        spec_with_the_real_nvidia_shape(&dir);
        let mut out = CdiEdits::default();
        resolve_cdi_device_in(&[dir.join("nvidia.json")], "nvidia.com/gpu=all", &mut out).unwrap();

        for node in ["/dev/nvidia0", "/dev/nvidiactl", "/dev/nvidia-uvm"] {
            assert!(
                out.devices
                    .iter()
                    .any(|d| d.starts_with(&format!("{node}:"))),
                "{node} em falta: {:?}",
                out.devices
            );
        }
        assert!(out.mounts.iter().any(|m| m.target == "/usr/bin/nvidia-smi"));
        assert!(out.mounts.iter().any(|m| m.target.contains("libcuda.so")));
        assert!(out.env.contains(&"NVIDIA_VISIBLE_DEVICES=void".to_string()));
        assert!(out.had_unexecuted_hooks);

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn resolve_all_does_not_duplicate_what_three_devices_repeat() {
        // `=all` matches "0", "GPU-<uuid>" and "all" — the same three nodes
        // three times — and the top-level edits must be merged ONCE, not once
        // per matched device.
        let dir = tmpdir("dedupe");
        spec_with_the_real_nvidia_shape(&dir);
        let mut out = CdiEdits::default();
        resolve_cdi_device_in(&[dir.join("nvidia.json")], "nvidia.com/gpu=all", &mut out).unwrap();

        let mut devices = out.devices.clone();
        devices.sort();
        let before = devices.len();
        devices.dedup();
        assert_eq!(
            before,
            devices.len(),
            "device nodes duplicados: {devices:?}"
        );
        assert_eq!(
            out.mounts
                .iter()
                .filter(|m| m.target == "/usr/bin/nvidia-smi")
                .count(),
            1,
            "os mounts de topo entraram mais do que uma vez"
        );
        assert_eq!(out.env.len(), 1, "env duplicado: {:?}", out.env);

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn resolve_named_device_also_gets_the_top_level_edits() {
        // A container asking for GPU 0 specifically needs the driver just as
        // much as one asking for all of them.
        let dir = tmpdir("nomeado");
        spec_with_the_real_nvidia_shape(&dir);
        let mut out = CdiEdits::default();
        resolve_cdi_device_in(&[dir.join("nvidia.json")], "nvidia.com/gpu=0", &mut out).unwrap();
        assert!(out.devices.iter().any(|d| d.starts_with("/dev/nvidiactl:")));
        assert!(out.mounts.iter().any(|m| m.target == "/usr/bin/nvidia-smi"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn other_vendor_spec_does_not_contribute_its_top_level_edits() {
        // Guard for the shape of the fix: the top-level merge happens only for
        // a spec that actually matched the requested vendor/class, otherwise an
        // unrelated vendor's spec sitting in /etc/cdi would leak its mounts
        // into every GPU container.
        let dir = tmpdir("vendor");
        spec_with_the_real_nvidia_shape(&dir);
        let other_vendor = serde_json::json!({
            "cdiVersion": "0.7.0",
            "kind": "intel.com/gpu",
            "containerEdits": {
                "mounts": [{"hostPath": "/opt/intel/lib", "containerPath": "/opt/intel/lib"}]
            },
            "devices": [{"name": "all", "containerEdits": {"deviceNodes": [{"path": "/dev/dri/renderD129"}]}}]
        });
        std::fs::write(dir.join("intel.json"), other_vendor.to_string()).unwrap();

        let mut out = CdiEdits::default();
        resolve_cdi_device_in(
            &[dir.join("nvidia.json"), dir.join("intel.json")],
            "nvidia.com/gpu=all",
            &mut out,
        )
        .unwrap();
        assert!(!out.mounts.iter().any(|m| m.target == "/opt/intel/lib"));
        assert!(!out.devices.iter().any(|d| d.contains("renderD129")));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn resolve_rejects_a_name_no_spec_declares() {
        let dir = tmpdir("ausente");
        spec_with_the_real_nvidia_shape(&dir);
        let mut out = CdiEdits::default();
        let err = resolve_cdi_device_in(&[dir.join("nvidia.json")], "nvidia.com/gpu=7", &mut out)
            .unwrap_err();
        assert!(format!("{err}").contains("not found"), "{err}");
        std::fs::remove_dir_all(&dir).ok();
    }
}
